export const termsContent = `
# Disclaimer & Terms of Use

**Last Updated:** February 2025

## 1. Not Medical Advice
NutriVision AI is an educational tool designed to provide estimates of nutritional content based on visual analysis. **It is not a medical device.**
*   The data provided (Calories, Glycemic Index, etc.) are **estimates only** generated by AI.
*   Do not use this app to make critical health decisions, calculate insulin dosages, or manage medical conditions without consulting a qualified healthcare professional.
*   Always verify nutritional information with official sources or packaging labels.

## 2. API Usage & Costs
This application uses the Google Gemini API.
*   You are required to provide your own API Key.
*   By using this app, you acknowledge that usage may incur costs billed directly to you by Google, depending on your API plan and usage volume.
*   NutriVision AI is not responsible for any charges incurred on your Google Cloud account.

## 3. Privacy Policy
*   **Local Storage:** Your API Key is stored locally in your browser's \`localStorage\`. It is sent directly to Google's servers to process your requests and is never sent to any other third-party server.
*   **Images:** Images you capture are sent to the Google Gemini API for analysis. They are not permanently stored by NutriVision AI, though they may be processed by Google in accordance with their [Google Cloud Data Privacy Policy](https://cloud.google.com/terms/data-privacy).
*   **History:** Your scan history is stored temporarily in your active session.

## 4. "As Is" Warranty
The software is provided "as is", without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability.

## 5. Acceptance
By entering your API Key and using NutriVision AI, you agree to these terms.
`;